# Generated by Django 6.1.1 on 2026-09-28 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('presenca', models.BooleanField(default=True)),
                ('acompanhantes', models.PositiveIntegerField(default=0)),
                ('tamanho_fralda', models.CharField(blank=True, choices=[('RN', 'RN'), ('P', 'P'), ('M', 'M'), ('G', 'G')], max_length=2)),
                ('data_confirmacao', models.DateTimeField(auto_now_add=True)),
                ('presente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evento.presente')),
            ],
        ),
    ]
