# Generated by Django 6.1.1 on 2026-09-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convidado',
            name='presenca',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='convidado',
            name='tamanho_fralda',
            field=models.CharField(blank=True, choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=2),
        ),
    ]
