# Generated by Django 6.1.1 on 2026-10-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_acompanhante'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhante',
            name='nome',
            field=models.CharField(default='Não informado', max_length=150),
            preserve_default=False,
        ),
    ]
