# Generated by Django 6.1.1 on 2026-10-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_acompanhante_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhante',
            name='mimo',
            field=models.CharField(blank=True, choices=[('naninha', 'Naninha'), ('kit_higiene', 'Kit higiene'), ('body', 'Body'), ('kit_cuidados', 'Kit cuidados')], max_length=20),
        ),
        migrations.AddField(
            model_name='convidado',
            name='mimo',
            field=models.CharField(blank=True, choices=[('naninha', 'Naninha'), ('kit_higiene', 'Kit higiene'), ('body', 'Body'), ('kit_cuidados', 'Kit cuidados')], max_length=20),
        ),
    ]
