# Generated by Django 6.1.1 on 2026-10-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0005_acompanhante_mimo_convidado_mimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhante',
            name='mimo',
            field=models.CharField(blank=True, choices=[('macacao', 'Macacão'), ('body', 'Body'), ('mijao', 'Mijão'), ('meia', 'Meia'), ('luvinha', 'Luvinha'), ('touca', 'Touca'), ('manta', 'Manta'), ('toalhinha_boca', 'Toalhinha de boca'), ('toalha_banho', 'Toalha de banho'), ('outros', 'Outros')], max_length=30),
        ),
        migrations.AlterField(
            model_name='acompanhante',
            name='tamanho_fralda',
            field=models.CharField(blank=True, choices=[('RN', 'Fralda RN'), ('P', 'Fralda P'), ('M', 'Fralda M'), ('G', 'Fralda G'), ('lenco', 'Lenço umedecido'), ('pomada', 'Pomada')], max_length=10),
        ),
        migrations.AlterField(
            model_name='convidado',
            name='mimo',
            field=models.CharField(blank=True, choices=[('macacao', 'Macacão'), ('body', 'Body'), ('mijao', 'Mijão'), ('meia', 'Meia'), ('luvinha', 'Luvinha'), ('touca', 'Touca'), ('manta', 'Manta'), ('toalhinha_boca', 'Toalhinha de boca'), ('toalha_banho', 'Toalha de banho'), ('outros', 'Outros')], max_length=30),
        ),
        migrations.AlterField(
            model_name='convidado',
            name='tamanho_fralda',
            field=models.CharField(blank=True, choices=[('RN', 'Fralda RN'), ('P', 'Fralda P'), ('M', 'Fralda M'), ('G', 'Fralda G'), ('lenco', 'Lenço umedecido'), ('pomada', 'Pomada')], max_length=10),
        ),
    ]
