# Generated by Django 6.1.1 on 2026-10-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0006_alter_acompanhante_mimo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presente',
            name='limite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
